### ISSUE TITLE
Server panics if server.log file does not already exist

### ISSUE THREAD

**Issue by scatternoodle** [scatternoodle/wflang#9]
Server panics if server.log file does not already exist. I don't think this is reasonable - server should create the log file if it doesn't exist. 

We already have logic that should be handling this, here: 

https://github.com/scatternoodle/wflang/blob/bea3f2d3242b22ed12a6d47474119280d7af4822/cmd/server/main.go#L31-L41

Example error log: 

> goroutine 1 [running]:
main.setupLogging({0x7ffda7003349?, 0xc000064740?}, 0x0?)
	/home/flinty/workspace/github.com/scatternoodle/wflang/cmd/server/main.go:40 +0x173
main.main()
	/home/flinty/workspace/github.com/scatternoodle/wflang/cmd/server/main.go:18 +0x45
[Error - 12:47:23 AM] Server process exited with code 2.
[Error - 12:47:23 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 12:47:23 AM] Connection to server got closed. Server will restart.
true
[Error - 12:47:23 AM] wflsrv client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
panic: error opening logfile: open editors/vscode/extension/server/logs/server.log: no such file or directory

**Comment by scatternoodle** [comment]
it's not the file - we're already creating with os.CREATE flag and have (redundant) handling afterword for path.NotFoundError 

It's because the directory didn't exist - this is because I deleted and recloned the repo - the server/log directory doesn't get committed to the repo because it's empty (the actual logfile is .gitignored).

I think we'll want to handle ensuring the dir is there during the extension init script.
